# Generated by Django 5.2.6 on 2025-09-21 23:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(max_length=50, unique=True)),
                ('origin_address', models.CharField(max_length=300)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_state', models.CharField(max_length=50)),
                ('origin_zip', models.CharField(max_length=10)),
                ('destination_address', models.CharField(max_length=300)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_state', models.CharField(max_length=50)),
                ('destination_zip', models.CharField(max_length=10)),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('planned_start_time', models.DateTimeField()),
                ('planned_end_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_distance', models.DecimalField(decimal_places=2, help_text='Estimated distance in miles', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('actual_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Actual distance traveled in miles', max_digits=8, null=True)),
                ('load_description', models.CharField(blank=True, max_length=200)),
                ('load_weight', models.PositiveIntegerField(blank=True, help_text='Load weight in pounds', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
                'ordering': ['-planned_start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Trip Started'), ('stop', 'Stop Completed'), ('fuel', 'Fuel Purchase'), ('inspection', 'Vehicle Inspection'), ('breakdown', 'Vehicle Breakdown'), ('delay', 'Delay Encountered'), ('complete', 'Trip Completed'), ('other', 'Other Event')], max_length=20)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField()),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional event data (fuel amount, cost, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Event',
                'verbose_name_plural': 'Trip Events',
                'db_table': 'trip_events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('fuel', 'Fuel Stop'), ('rest', 'Rest Stop'), ('pickup', 'Pickup'), ('delivery', 'Delivery'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20)),
                ('stop_order', models.PositiveIntegerField(default=1)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('planned_arrival', models.DateTimeField()),
                ('planned_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
                'db_table': 'trip_stops',
                'ordering': ['trip', 'stop_order'],
                'unique_together': {('trip', 'stop_order')},
            },
        ),
    ]
